---
type: docker
kind: pipeline
name: default

steps:
- name: test-node-current-alpine
  image: node:current-alpine
  commands: [cp -R . /src, cd /src, npm ci, npm test]

- name: test-node-22-debian
  image: node:22
  commands: [cp -R . /src, cd /src, npm ci, npm test]

- name: test-node-22-alpine
  image: node:22-alpine
  commands: [cp -R . /src, cd /src, npm ci, npm test]

- name: test-node-20-debian
  image: node:20
  commands: [cp -R . /src, cd /src, npm ci, npm test]

- name: test-node-20-alpine
  image: node:20-alpine
  commands: [cp -R . /src, cd /src, npm ci, npm test]

- name: test-node-18-alpine
  image: node:18-alpine
  commands: [cp -R . /src, cd /src, npm ci, npm test]

- name: test-node-18-debian
  image: node:18
  commands: [cp -R . /src, cd /src, npm ci, npm test]

- name: release
  image: livingdocs/semantic-release:v2.1.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  depends_on:
  - test-node-current-alpine
  - test-node-22-debian
  - test-node-22-alpine
  - test-node-20-debian
  - test-node-20-alpine
  - test-node-18-debian
  - test-node-18-alpine

trigger:
  event: [push]
---
kind: signature
hmac: e2aabe6feb8e9568c8732a0b2d6643d2f8796ad34be11bc15a0cd0dbcdd34cf4

...
