---
type: docker
kind: pipeline
name: default

steps:
- name: test-node-current-alpine
  image: node:current-alpine
  commands: [cp -R . /src, cd /src, npm ci, npm test]

- name: test-node-16-debian
  image: node:16
  commands: [cp -R . /src, cd /src, npm ci, npm test]

- name: test-node-16-alpine
  image: node:16-alpine
  commands: [cp -R . /src, cd /src, npm ci, npm test]

- name: test-node-14-debian
  # node:14 (debian stretch) uses a glibc version, which is too old
  # we'll need to test against buster
  image: node:14-buster
  commands: [cp -R . /src, cd /src, npm ci, npm test]

- name: test-node-14-alpine
  image: node:14-alpine
  commands: [cp -R . /src, cd /src, npm ci, npm test]

- name: release
  image: livingdocs/semantic-release:v1.2.1
  environment:
    GH_TOKEN:
      from_secret: gh_token
    NPM_TOKEN:
      from_secret: npm_token
  depends_on:
  - test-node-current-alpine
  - test-node-16-debian
  - test-node-14-debian
  - test-node-16-alpine
  - test-node-14-alpine

trigger:
  event: [push]
---
kind: signature
hmac: 053f9095e742265c30113aeaae26ddd76dfb3aa3ca5422286cd11f78138951bf

...
